-- Restart the DOMAIN_CONFIGIDSEQ, CONFIG_VALUESIDSEQ and CONFIG_ATTRIBUTESIDSEQ sequences to ensure they start from the correct value
BEGIN
  DECLARE max_id INTEGER DEFAULT 0;

  -- Get the max DOMAIN_CONFIGID
  SELECT COALESCE(MAX(DOMAIN_CONFIGID), 0)
  INTO max_id
  FROM DOMAIN_CONFIG;

  -- Restart the sequence with max_id + 1
  EXECUTE IMMEDIATE 'ALTER SEQUENCE DOMAIN_CONFIGIDSEQ RESTART WITH ' || (max_id + 1);
END

BEGIN
  DECLARE max_id INTEGER DEFAULT 0;

  -- Get the max DOMAIN_CONFIGID
  SELECT COALESCE(MAX(CONFIG_VALUESID), 0)
  INTO max_id
  FROM CONFIG_VALUES;

  -- Restart the sequence with max_id + 1
  EXECUTE IMMEDIATE 'ALTER SEQUENCE CONFIG_VALUESIDSEQ RESTART WITH ' || (max_id + 1);
END

BEGIN
  DECLARE max_id INTEGER DEFAULT 0;

  -- Get the max CONFIG_ATTRIBUTESID
  SELECT COALESCE(MAX(CONFIG_ATTRIBUTESID), 0)
  INTO max_id
  FROM CONFIG_ATTRIBUTES;

  -- Restart the sequence with max_id + 1
  EXECUTE IMMEDIATE 'ALTER SEQUENCE CONFIG_ATTRIBUTESIDSEQ RESTART WITH ' || (max_id + 1);
END

-- Delete existing entries in DOMAIN_CONFIG, CONFIG_VALUES and CONFIG_ATTRIBUTES for MAMS_MOBILE_METERSTATUS
DELETE FROM DOMAIN_CONFIG WHERE DOMAIN = 'MAMS_MOBILE_METERSTATUS';
DELETE FROM CONFIG_VALUES WHERE DOMAIN = 'MAMS_MOBILE_METERSTATUS';
DELETE FROM CONFIG_ATTRIBUTES WHERE DOMAIN = 'MAMS_MOBILE_METERSTATUS';

-- Insert new entries into DOMAIN_CONFIG, CONFIG_VALUES and CONFIG_ATTRIBUTES for MAMS_MOBILE_METERSTATUS

-- DOMAIN_CONFIG
INSERT INTO DOMAIN_CONFIG (DOMAIN_CONFIGID, DESCRIPTION, HASLD, "DOMAIN", LANGCODE, "SOURCE")
VALUES (DOMAIN_CONFIGIDSEQ.NEXTVAL, "Domain defining user parameters by security group", 0, 'MAMS_MOBILE_CONFIG', NULL, NULL);

-- CONFIG_VALUES
INSERT INTO CONFIG_VALUES (CONFIG_VALUESID, HASLD, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 0, 'MAMS.LAB', 'SEND TO LAB FOR RECODING', 'USED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_METERSTATUS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO CONFIG_VALUES (CONFIG_VALUESID, HASLD, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 0, 'MAMS.LAB', 'SEND TO LAB FOR RECODING', 'SCRAPPABLE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_METERSTATUS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO CONFIG_VALUES (CONFIG_VALUESID, HASLD, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 0, 'MAMS.RDC.DISPATCH', 'NEW', 'OBSOLETE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_METERSTATUS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO CONFIG_VALUES (CONFIG_VALUESID, HASLD, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 0, 'MAMS.RDC.DISPATCH', 'OBSOLETE', 'NEW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_METERSTATUS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO CONFIG_VALUES (CONFIG_VALUESID, HASLD, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 0, 'MAMS.RDC.RECEIVING', 'OBSOLETE', 'NEW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_METERSTATUS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO CONFIG_VALUES (CONFIG_VALUESID, HASLD, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 0, 'MAMS.RDC.RECEIVING', 'NEW', 'OBSOLETE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_METERSTATUS', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- CONFIG_ATTRIBUTES
INSERT INTO CONFIG_ATTRIBUTES (CONFIG_ATTRIBUTESID, DESCRIPTION, COLMAP, COLMAPDESC, "DOMAIN", HASLD)
VALUES (CONFIG_ATTRIBUTESIDSEQ.NEXTVAL, NULL, 'ALNVAL1', 'IDENTIFIES THE SECURITY GROUP', 'MAMS_MOBILE_METERSTATUS', 0);

INSERT INTO CONFIG_ATTRIBUTES (CONFIG_ATTRIBUTESID, DESCRIPTION, COLMAP, COLMAPDESC, "DOMAIN", HASLD)
VALUES (CONFIG_ATTRIBUTESIDSEQ.NEXTVAL, NULL, 'ALNVAL2', 'THE CURRENT STATUS OF THE METER BEFORE TRANSITION', 'MAMS_MOBILE_METERSTATUS', 0);

INSERT INTO CONFIG_ATTRIBUTES (CONFIG_ATTRIBUTESID, DESCRIPTION, COLMAP, COLMAPDESC, "DOMAIN", HASLD)
VALUES (CONFIG_ATTRIBUTESIDSEQ.NEXTVAL, NULL, 'ALNVAL3', 'THE TARGET STATUS THE METER CAN CHANGE TO', 'MAMS_MOBILE_METERSTATUS', 0);

-- Commit the transactions
COMMIT;