
BEGIN
  DECLARE max_id INTEGER DEFAULT 0;

  -- Get the max DOMAIN_CONFIGID
  SELECT COALESCE(MAX(DOMAIN_CONFIGID), 0)
  INTO max_id
  FROM DOMAIN_CONFIG;

  -- Restart the sequence with max_id + 1
  EXECUTE IMMEDIATE 'ALTER SEQUENCE DOMAIN_CONFIGIDSEQ RESTART WITH ' || max_id;
END

BEGIN
  DECLARE max_id INTEGER DEFAULT 0;

  -- Get the max DOMAIN_CONFIGID
  SELECT COALESCE(MAX(CONFIG_VALUESID), 0)
  INTO max_id
  FROM CONFIG_VALUES;

  -- Restart the sequence with max_id + 1
  EXECUTE IMMEDIATE 'ALTER SEQUENCE CONFIG_VALUESIDSEQ RESTART WITH ' || max_id;
END

DELETE FROM DOMAIN_CONFIG WHERE DOMAIN = 'MAMS_MOBILE_CONFIG';
DELETE FROM CONFIG_VALUES WHERE DOMAIN = 'MAMS_MOBILE_CONFIG';

INSERT INTO MAXIMO.DOMAIN_CONFIG (DOMAIN_CONFIGID, DESCRIPTION, HASLD, "DOMAIN", LANGCODE, "SOURCE")
VALUES (DOMAIN_CONFIGIDSEQ.NEXTVAL, NULL, 0, 'MAMS_MOBILE_CONFIG', NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'CNC_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'PROJECT_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO PROJECT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'RDC_SERVICE_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'TSU_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO TSU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'EP_SAPRESERVATION', 'N_SAPRESERV:MY CNC SAP RESERVATION TO EP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CNC meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'EP_SERVICE_RECEIVE', 'SHIPREC:shipement query', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'EP_OBS_RECEIVE', 'SHIPREC:shipement query', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'EP_SCRAP_RECEIVE', 'SHIPREC:shipement query', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'CNC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CNC meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', 'LAB_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CNC meters shipment from LAB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CPM meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY LAB meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', 'CPM_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY LAB meters shipment from CPM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', 'CNC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY LAB meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', 'RDC_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', 'CNC_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', 'CPM_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO CPM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', 'PROJECT_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO PROJECT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', 'CNC_SERVICE_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC Serviceable meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', 'CNC_OBS_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC Obsolete meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', 'CNC_SCRAP_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC Scrappable meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', 'CPM_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC meters shipment from CPM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', 'LAB_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC meters shipment from LAB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', 'METER_RECEIVE', 'N_METERSRECEIPTS:MY PO TO BE RECEIVED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Receiving', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_RDC_Issuing', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CPM', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_CNC', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MOB_LAB', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
