
BEGIN
  DECLARE max_id INTEGER DEFAULT 0;

  -- Get the max DOMAIN_CONFIGID
  SELECT COALESCE(MAX(DOMAIN_CONFIGID), 0)
  INTO max_id
  FROM DOMAIN_CONFIG;

  -- Restart the sequence with max_id + 1
  EXECUTE IMMEDIATE 'ALTER SEQUENCE DOMAIN_CONFIGIDSEQ RESTART WITH ' || max_id;
END

BEGIN
  DECLARE max_id INTEGER DEFAULT 0;

  -- Get the max DOMAIN_CONFIGID
  SELECT COALESCE(MAX(CONFIG_VALUESID), 0)
  INTO max_id
  FROM CONFIG_VALUES;

  -- Restart the sequence with max_id + 1
  EXECUTE IMMEDIATE 'ALTER SEQUENCE CONFIG_VALUESIDSEQ RESTART WITH ' || max_id;
END
COMMIT;

DELETE FROM DOMAIN_CONFIG WHERE DOMAIN = 'MAMS_MOBILE_CONFIG';
DELETE FROM CONFIG_VALUES WHERE DOMAIN = 'MAMS_MOBILE_CONFIG';
COMMIT;

INSERT INTO MAXIMO.DOMAIN_CONFIG (DOMAIN_CONFIGID, DESCRIPTION, HASLD, "DOMAIN", LANGCODE, "SOURCE")
VALUES (DOMAIN_CONFIGIDSEQ.NEXTVAL, NULL, 0, 'MAMS_MOBILE_CONFIG', NULL, NULL);
COMMIT;

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CPM meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', 'LAB_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CPM meters shipment from LAB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY LAB meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', 'CPM_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY LAB meters shipment from CPM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', 'CNC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY LAB meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', 'RDC_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', 'CNC_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', 'CPM_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO CPM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', 'PROJECT_SAPRESERVATION', 'N_SAPRESERV:My RDC SAP RESERVATION TO PROJECT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', 'CNC_SERVICE_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC Serviceable meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', 'CNC_OBS_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC Obsolete meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', 'CNC_SCRAP_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC Scrappable meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', 'CPM_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC meters shipment from CPM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', 'LAB_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY RDC meters shipment from LAB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', 'METER_RECEIVE', 'N_METERSRECEIPTS:MY PO TO BE RECEIVED', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.RECEIVING', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'TIMEOUT', '60', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'KEEPDATAFOR', '24', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'CONNECTIONMODE', 'AutoSync', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'LOADTRANSACTINALDATA', 'false', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'SAVEUSERNAME', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'SAVEPASSWORD', 'true', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'DATEPATTERN', 'YYYY/MM/DD', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.RDC.DISPATCH', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CPM', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.LAB', NULL, NULL, 'DATETIMEPATTERN', 'YYYY/MM/DD HH:mm', NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'CNC_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'PROJECT_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO PROJECT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'RDC_SERVICE_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'TSU_SAPRESERVATION', 'N_SAPRESERV:My CNC SAP RESERVATION TO TSU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'EP_SAPRESERVATION', 'N_SAPRESERV:MY CNC SAP RESERVATION TO EP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'RDC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CNC meters shipment from RDC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'EP_SERVICE_RECEIVE', 'SHIPREC:shipement query', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'EP_OBS_RECEIVE', 'SHIPREC:shipement query', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'EP_SCRAP_RECEIVE', 'SHIPREC:shipement query', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'CNC_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CNC meters shipment from CNC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO MAXIMO.CONFIG_VALUES (CONFIG_VALUESID, ALNVAL1, ALNVAL2, ALNVAL3, ALNVAL4, ALNVAL5, DATE1, DATE2, DATE3, DATE4, DATE5, "DOMAIN", NUMVAL1, NUMVAL2, NUMVAL3, NUMVAL4, NUMVAL5, N_EXTERNALSYSTEM, N_EXTERNALUSERID)
VALUES (CONFIG_VALUESIDSEQ.NEXTVAL, 'MAMS.CNC.STORES', 'LAB_RECEIVE', 'N_METERS_SHIPMENTRECEIPTS:MY CNC meters shipment from LAB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MAMS_MOBILE_CONFIG', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;